### ISSUE TITLE
kong distro page.

### ISSUE THREAD

**Issue by sonicaghi** [arsdehnel/kong-tf#1]
hi - nice work. if this gets finished we will include in the getkong.org/install distro page.

**Comment by arsdehnel** [comment]
Good deal. I'm having an issue with Kong finding Cassandra right now but I'm optimistic that's the only barrier left to have it working.

**Comment by arsdehnel** [comment]
I think this is (finally) ready for use by others.  i've got a few things that i'm going to keep working on around autoscaling and some subnet enhancements but that's just extra.  The repo should work as it is right now.
